import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

const RubikSans = Rubik({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${RubikSans.variable}  antialiased`}>{children}</body>
    </html>
  );
}
